library(nimble)
library(coda)
library(httr)
source("../R_scripts/Plotting/HPDregion.R")
source("../R_scripts/Analysis/nimbleIndicator.R")
load("../Data/EuroClimCon_v2.RData")
source("../R_scripts/Analysis/NimblePoisTS_change_v2.R")
